{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Test BE Orento",
    "contact": {}
  },
  "host": "localhost:8000",
  "basePath": "/",
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ],
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/register": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Register",
        "operationId": "Register",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "formData",
            "description": "",
            "required": true,
            "type": "string"
          },
          {
            "name": "email",
            "in": "formData",
            "description": "",
            "required": true,
            "type": "string"
          },
          {
            "name": "password",
            "in": "formData",
            "description": "",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "success": true,
                "message": "Ok",
                "data": {
                  "name": "wiwijuwita",
                  "email": "wijuwita@gmail.com",
                  "updated_at": "2021-10-23T11:51:48.000000Z",
                  "created_at": "2021-10-23T11:51:48.000000Z",
                  "id": 1
                }
              }
            },
            "headers": {
              "Host": {
                "type": "string",
                "default": "localhost:8000"
              },
              "Date": {
                "type": "string",
                "default": "Sat, 23 Oct 2021 11:51:49 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "close"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "PHP/7.4.21"
              },
              "Cache-Control": {
                "type": "string",
                "default": "no-cache, private"
              }
            },
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          }
        },
        "deprecated": false
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Login",
        "operationId": "Login",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "formData",
            "description": "",
            "required": true,
            "type": "string"
          },
          {
            "name": "password",
            "in": "formData",
            "description": "",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "success": true,
                "message": "Ok",
                "data": {
                  "id": 1,
                  "name": "wiwijuwita",
                  "email": "wijuwita@gmail.com",
                  "created_at": "2021-10-23T11:51:48.000000Z",
                  "updated_at": "2021-10-23T12:14:46.000000Z",
                  "token": "d2lqdXdpdGFAZ21haWwuY29tOmExYjFBMUIy"
                }
              }
            },
            "headers": {
              "Host": {
                "type": "string",
                "default": "localhost:8000"
              },
              "Date": {
                "type": "string",
                "default": "Sat, 23 Oct 2021 12:17:20 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "close"
              },
              "X-Powered-By": {
                "type": "string",
                "default": "PHP/7.4.21"
              },
              "Cache-Control": {
                "type": "string",
                "default": "no-cache, private"
              }
            },
            "schema": {
              "$ref": "#/definitions/SuccessResponse1"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "SuccessResponse": {
      "type": "object",
      "required": [
        "data",
        "message",
        "success"
      ],
      "properties": {
        "success": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        }
      },
      "title": "SuccessResponse",
      "example": {
        "success": true,
        "message": "Ok",
        "data": {
          "name": "wiwijuwita",
          "email": "wijuwita@gmail.com",
          "updated_at": "2021-10-23T11:51:48.000000Z",
          "created_at": "2021-10-23T11:51:48.000000Z",
          "id": 1
        }
      }
    },
    "Data": {
      "type": "object",
      "required": [
        "created_at",
        "email",
        "id",
        "name",
        "updated_at"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "Data",
      "example": {
        "name": "wiwijuwita",
        "email": "wijuwita@gmail.com",
        "updated_at": "2021-10-23T11:51:48.000000Z",
        "created_at": "2021-10-23T11:51:48.000000Z",
        "id": 1
      }
    },
    "SuccessResponse1": {
      "type": "object",
      "required": [
        "data",
        "message",
        "success"
      ],
      "properties": {
        "success": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data1"
        }
      },
      "title": "SuccessResponse1",
      "example": {
        "success": true,
        "message": "Ok",
        "data": {
          "id": 1,
          "name": "wiwijuwita",
          "email": "wijuwita@gmail.com",
          "created_at": "2021-10-23T11:51:48.000000Z",
          "updated_at": "2021-10-23T12:14:46.000000Z",
          "token": "d2lqdXdpdGFAZ21haWwuY29tOmExYjFBMUIy"
        }
      }
    },
    "Data1": {
      "type": "object",
      "required": [
        "created_at",
        "email",
        "id",
        "name",
        "token",
        "updated_at"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "token": {
          "type": "string"
        }
      },
      "title": "Data1",
      "example": {
        "id": 1,
        "name": "wiwijuwita",
        "email": "wijuwita@gmail.com",
        "created_at": "2021-10-23T11:51:48.000000Z",
        "updated_at": "2021-10-23T12:14:46.000000Z",
        "token": "d2lqdXdpdGFAZ21haWwuY29tOmExYjFBMUIy"
      }
    }
  }
}